version: '3.9'
services:
  influxdb:
    image: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: defaultOrg
      DOCKER_INFLUXDB_INIT_BUCKET: defaultBucket
      DOCKER_INFLUXDB_INIT_RETENTION: 0
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mGKNA3ucyOT2rnIuxmGYQAbnrYkBGaT0Piiotl2AFurXVbCl8ExjRok5I9IKI5f94prJziCGSezz7J_JQUGkBg==
    ports:
      - 8086:8086
    expose:
      - "8086"
    volumes:
      - influxdbv1:/var/lib/influxdb
      - influxdbv2:/var/lib/influxdb2
      - influxdbconfig:/etc/influxdb2
    container_name: influxdb
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    expose:
      - "9093"
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
      # If the consumer/producer is not on the same machine kafka is running, then the OUTSIDE listener must be the IP of the machine instead of localhost,
      # otherwise it is telling clients that they can send and consume messages from localhost which ends up pointing to the client and not the server. 
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092,EXTERNAL://192.168.0.38:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "TelemetryData:5:1"
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - kafka
      - grafana
      - zookeeper
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://kafka:9093" ]
      interval: 30s
      timeout: 10s
      retries: 5
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    expose:
      - 3000
    container_name: grafana

volumes:
  influxdbv1:
  influxdbv2:
  influxdbconfig:
